name: push_to_azure_storage

on:
  push:
    branches: [main]
    paths:
      - 'dtmi/**/*.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: digimaun/get-changed-files@v2

      - name: CLI push files
        uses: azure/CLI@v1
        with:
          inlineScript: |
            for changed_file in ${{ steps.files.outputs.added_modified }}; do
              if [[ ${changed_file} =~ ^dtmi([\/\\][a-z0-9_]+){2,}-([1-9][0-9]{0,8}).json$ ]]; then
                echo "Submitting ${changed_file} to Azure Storage"
                az storage blob upload --connection-string "${{ secrets.STORAGE_CONNECTION_STRING }}" --container-name '$web' --name "${changed_file}" --file "${changed_file}" --no-progress
              else
                echo "Skipping ${changed_file}. It doesn't appear to be a DTDL document."
              fi
            done
