name: validate-files

on:
  pull_request:
    branches: [main]
    paths:
      - 'dtmi/**'

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: digimaun/get-changed-files@v2

      - name: npm install
        run: npm install

      - name: check DTMI path convention
        run: node .github/workflows/validate-files.js ${{steps.files.outputs.added_modified}}

      - name: check global IDs 
        run: node .github/workflows/validate-ids.js ${{steps.files.outputs.added_modified}}

      - name: check dependencies 
        run: node .github/workflows/validate-deps.js ${{steps.files.outputs.added_modified}}
